spring:
  messages:
    baseName: i18n/messages
    encoding: UTF-8
    fallbackToSystemLocale: false

test:
  countAnsweredQuestionsForPass: 3
  locale: en-US
  fileNameByLocaleTag:
    en-US: questions.csv
    ru-RU: questions_ru.csv